-- this is hard to test...either way, it's a with others exception
--procedure t is
--begin
--  raise;  -- raise nothing
--exception when others =>
--  put_line( "exception raised" );
--end t;

